// <auto-generated />
using System;
using GestionFermeWebApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GestionFermeWebApi.Migrations
{
    [DbContext(typeof(GestionFermeConetxt))]
    partial class GestionFermeConetxtModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GestionFermeWebApi.Models.Ferme", b =>
                {
                    b.Property<int>("FermeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("adresse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("cinPopr")
                        .HasColumnType("int")
                        .HasMaxLength(50);

                    b.Property<DateTime>("dateAdhesion")
                        .HasColumnType("datetime2");

                    b.Property<string>("delegation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("gouveroratFerme")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nomFerme")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nomProp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("numTelProp")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FermeId");

                    b.ToTable("Ferme");
                });
#pragma warning restore 612, 618
        }
    }
}
